
## Relatório exportar informações N308

## Bibliotecas necessárias

library(DBI)
library(dplyr)
library(reshape2)
library(googlesheets4)

## conexão com banco replica 

con2 <- dbConnect(odbc::odbc(), "reproreplica")


cccust<- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','R','SR')),

PED AS (SELECT P.ID_PEDIDO,
             P.EMPCODIGO,
              PCC.CCCODIGO,
               PEDDTBAIXA
              FROM PEDID P
INNER JOIN FIS ON P.FISCODIGO1=FIS.FISCODIGO
 INNER JOIN PDCTCUSTO PCC ON P.ID_PEDIDO  = PCC.ID_PEDIDO 
   WHERE PEDDTBAIXA BETWEEN '01.01.2022' AND 'TODAY' AND 
     PEDSITPED<>'C' AND 
      PEDLCFINANC IN ('S', 'L','N'))

SELECT  PD.EMPCODIGO,CCCODIGO,EXTRACT (MONTH FROM PEDDTBAIXA) AS MES
 ,SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA 
 FROM PDPRD PD
  INNER JOIN PED P ON P.ID_PEDIDO=PD.ID_PEDIDO
  WHERE CCCODIGO='F4'
  GROUP BY 1,2,3")


View(cccust)


range_write("1haOMs9FvfdDeCnfgGC3fiM8FYzfPUjTeADzt_iS2u80",data=cccust,sheet = "RESUMO",
            range = "A1",reformat = FALSE) 


ELECT PED.PEDDTEMIS DATA 
, SUM(COALESCE(PP.PDPUNITLIQUIDO,0) * COALESCE(PP.PDPQTDADE,0)) + SUM(COALESCE(PP.PDPVRFRETE,0)) PEDVRTOTAL,
CL.CLINOMEFANT NOME,
DECODE(EXTRACT (MONTH FROM PEDDTEMIS), 1, 'JAN', 2, 'FEV', 3, 'MAR',4,'ABR') AS MES,
CL.CLICODIGO CLICODIGO,
PED.EMPCODIGO,
PCC.CCCODIGO
FROM PEDID PED 
LEFT JOIN PDPRD PP      ON PP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN TBFIS FIS     ON PP.FISCODIGO = FIS.FISCODIGO
LEFT JOIN PDCTCUSTO PCC ON PED.ID_PEDIDO  = PCC.ID_PEDIDO 
LEFT JOIN CLIEN CL      ON (PED.CLICODIGO = CL.CLICODIGO)
LEFT JOIN ENDCLI ED     ON (PED.CLICODIGO = ED.CLICODIGO AND PED.ENDCODIGO = ED.ENDCODIGO)
LEFT JOIN CIDADE CID    ON (ED.CIDCODIGO  = CID.CIDCODIGO)
LEFT JOIN ZONA    ZO  ON ZO.ZOCODIGO   = ED.ZOCODIGO
WHERE PED.ID_PEDIDO IS NOT NULL
AND ( PED.PEDDTEMIS BETWEEN @#DATE#Emissao_Inicial@ AND @#DATE#Emissao_Final@)
        AND ( PED.PEDSITPED = 'F' OR PED.PEDSITPED = 'A')
      AND (PP.PDPLCFINAN = 'S' AND PED.PEDLCFINANC <> 'L' OR  PED.PEDLCFINANC = 'L' AND PP.PDPLCFINAN = 'S')
      AND (PP.PDPLCETQ = 'S' OR PP.PDPLCETQ = 'N' OR PP.PDPLCETQ = 'L')
      AND ( FIS.FISTPNATOP = 'V' OR  FIS.FISTPNATOP = 'SR' OR  FIS.FISTPNATOP = 'R')
      GROUP BY PED.PEDDTEMIS,CLICODIGO,NOME,PED.EMPCODIGO,PCC.CCCODIGO