

## Bibliotecas necessárias

library(DBI)
library(dplyr)
library(googlesheets4)

## conexão com banco replica 

con2 <- dbConnect(odbc::odbc(), "reproreplica")


rep_243 <- dbGetQuery(con2,"
WITH CLI AS (SELECT DISTINCT CLIEN.CLICODIGO,CLINOMEFANT,GCLCODIGO
             FROM CLIEN
             WHERE CLICLIENTE='S' AND CLICODIGO=65),

FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISCODIGO IN ('5.117','6.117')),

PED AS (SELECT ID_PEDIDO,FISCODIGO1,PEDCODIGO,P.CLICODIGO,PEDDTEMIS,PEDDTBAIXA,PEDORIGEM,TPCODIGO FROM PEDID P
        INNER JOIN FIS F ON P.FISCODIGO1=F.FISCODIGO
        WHERE PEDDTEMIS BETWEEN '01.06.2022' AND 'TODAY' AND PEDSITPED<>'C'),
          
          AUX AS (SELECT PROCODIGO,PROCODIGO2,IIF(PROCODIGO2 IS NULL,PROCODIGO,PROCODIGO2)CHAVE,
                  PROTIPO FROM PRODU)
        
        
        SELECT PD.ID_PEDIDO,FISCODIGO1,PEDDTEMIS, CLICODIGO,PD.PROCODIGO,
        CHAVE,PDPDESCRICAO,
        SUM(PDPQTDADE) QTD,SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA  
        FROM PDPRD PD
        INNER JOIN PED P ON PD.ID_PEDIDO=P.ID_PEDIDO
        INNER JOIN AUX A ON PD.PROCODIGO=A.PROCODIGO
        
        GROUP BY 1,2,3,4,5,6,7 ORDER BY PEDDTEMIS DESC")


range_write("1EqLttJ74cEaDro1FrEeJ1hSyp-qF5GjeAwNVvziwOXs",data=rep_243,sheet = "CONSUMO 243 - MES VIGENTE",
            range = "B1",reformat = FALSE) 


rep_243 %>% summarize(v=sum(VRVENDA))