## TEST

sales_cli_vlx_2021 <- dbGetQuery(con2,"
WITH CLI AS (SELECT DISTINCT CLIEN.CLICODIGO,CLINOMEFANT
  FROM CLIEN
   WHERE CLICLIENTE='S'),
  
FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),
  
PED AS (SELECT ID_PEDIDO,PEDDTBAIXA,P.CLICODIGO FROM PEDID P
   INNER JOIN FIS F ON P.FISCODIGO1=F.FISCODIGO
    INNER JOIN CLI C ON P.CLICODIGO=C.CLICODIGO
     WHERE PEDSITPED<>'C' AND PEDDTBAIXA BETWEEN '01.01.2021' AND '31.12.2021'),
     
AUX AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=57)     

SELECT PEDDTBAIXA,
P.CLICODIGO,
 SUM(PDPQTDADE) QTD,
  SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA  
  FROM PDPRD PD
   INNER JOIN PED P ON PD.ID_PEDIDO=P.ID_PEDIDO
    INNER JOIN AUX ON PD.PROCODIGO= AUX.PROCODIGO
     GROUP BY 1,2")

save(sales_cli_vlx_2021,file =  "C:\\Users\\Repro\\Documents\\R\\ADM\\REPORT\\BASES\\sales_cli_vlx_2021.RData")


sales_cli_kdk_2021 <- dbGetQuery(con2,"
WITH CLI AS (SELECT DISTINCT CLIEN.CLICODIGO,CLINOMEFANT
  FROM CLIEN
   WHERE CLICLIENTE='S'),
  
FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),
  
PED AS (SELECT ID_PEDIDO,PEDDTBAIXA,P.CLICODIGO FROM PEDID P
   INNER JOIN FIS F ON P.FISCODIGO1=F.FISCODIGO
    INNER JOIN CLI C ON P.CLICODIGO=C.CLICODIGO
     WHERE PEDSITPED<>'C' AND PEDDTBAIXA BETWEEN '01.01.2021' AND '31.12.2021'),
     
AUX AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=24)     

SELECT PEDDTBAIXA,
P.CLICODIGO,
 SUM(PDPQTDADE) QTD,
  SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA  
  FROM PDPRD PD
   INNER JOIN PED P ON PD.ID_PEDIDO=P.ID_PEDIDO
    INNER JOIN AUX ON PD.PROCODIGO= AUX.PROCODIGO
     GROUP BY 1,2")

save(sales_cli_kdk_2021,file =  "C:\\Users\\Repro\\Documents\\R\\ADM\\REPORT\\BASES\\sales_cli_kdk_2021.RData")


sales_cli_mrepro_2021 <- dbGetQuery(con2,"
WITH CLI AS (SELECT DISTINCT CLIEN.CLICODIGO,CLINOMEFANT
  FROM CLIEN
   WHERE CLICLIENTE='S'),
  
FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),
  
PED AS (SELECT ID_PEDIDO,PEDDTBAIXA,P.CLICODIGO FROM PEDID P
   INNER JOIN FIS F ON P.FISCODIGO1=F.FISCODIGO
    INNER JOIN CLI C ON P.CLICODIGO=C.CLICODIGO
     WHERE PEDSITPED<>'C' AND PEDDTBAIXA BETWEEN '01.01.2021' AND '31.12.2021'),
     
AUX AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO IN (158,159,135,128,106,189))     

SELECT PEDDTBAIXA,
P.CLICODIGO,
 SUM(PDPQTDADE) QTD,
  SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA  
  FROM PDPRD PD
   INNER JOIN PED P ON PD.ID_PEDIDO=P.ID_PEDIDO
    INNER JOIN AUX ON PD.PROCODIGO= AUX.PROCODIGO
     GROUP BY 1,2")


save(sales_cli_mrepro_2021,file =  "C:\\Users\\Repro\\Documents\\R\\ADM\\REPORT\\BASES\\sales_cli_mrepro_2021.RData")



sales_cli_geral_2021 <- dbGetQuery(con2,"
WITH CLI AS (SELECT DISTINCT CLIEN.CLICODIGO,CLINOMEFANT
  FROM CLIEN
   WHERE CLICLIENTE='S'),
  
FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),
  
PED AS (SELECT ID_PEDIDO,PEDDTBAIXA,P.CLICODIGO FROM PEDID P
   INNER JOIN FIS F ON P.FISCODIGO1=F.FISCODIGO
    INNER JOIN CLI C ON P.CLICODIGO=C.CLICODIGO
     WHERE PEDSITPED<>'C' AND PEDDTBAIXA BETWEEN '01.01.2021' AND '31.12.2021')

SELECT PEDDTBAIXA,
P.CLICODIGO,
 SUM(PDPQTDADE) QTD,
  SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA  
  FROM PDPRD PD
   INNER JOIN PED P ON PD.ID_PEDIDO=P.ID_PEDIDO
     GROUP BY 1,2")

save(sales_cli_geral_2021,file =  "C:\\Users\\Repro\\Documents\\R\\ADM\\REPORT\\BASES\\sales_cli_geral_2021.RData")

