
WITH TBPRECO AS (
 SELECT TBPCODIGO
  FROM TABPRECO
   WHERE TBPDESCRICAO LIKE '%TRATAMENTO BONIFICADO%')
  
  
  SELECT DISTINCT CLICODIGO
   FROM CLITBP C
    INNER JOIN TBPRECO T ON C.TBPCODIGO=T.TBPCODIGO
                               